# Generated by Django 3.0.6 on 2020-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donat', '0002_auto_20200604_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
    ]
